### ISSUE TITLE
web hook does not support subdomains

### ISSUE THREAD

**Issue by davlloyd** [Dopingus/cert-manager-webhook-dynu#10]
When attempting to use a deny subdomain of a registered domain, the TXT records are created in the root domain and not the sub domain. This is as a result of using the dyne API call `https://api.dynu.com/v2/dns/getroot/<hostname>` to determine the DNS domain. This results in the parent DNS domain being returned as the domainName and the subdomain and hostname being combined and listed as the 'node' in the response. 

There does not appear to be a way to identify subdomains in the dynu APIs and have fed this back to them via their forum. I am raising this as an issue here in case this is still being maintained instead of forking off to work around the issue.

**Comment by davlloyd** [comment]
I have forked the code and added the logic for supporting subdomains. Also updated helm charts with new RBAC requirements. Will create a pull request once testing is completed

**Comment by Dopingus** [comment]
Hi @davlloyd,

thanks for reporting and fixing this issue. I haven't had the time to take a look at it yet.

Will check and merge as soon as you're ready.


Thanks & Regards

**Comment by davlloyd** [comment]
Closed due to being fixed in latest update
