### ISSUE TITLE
Pages build action not running

### ISSUE THREAD

**Issue by davlloyd** [Dopingus/cert-manager-webhook-dynu#12]
I went to test the latest update but it failed with the RABC issue. This is because Helm updates are not getting published as the Pages Build and Deployment action has not run to publish the new Helm charts

**Comment by anon-software** [comment]
If you open the actions for Release Chart action, you will see a warning with a link explaining it in more detail. The bottom line is that they deprecated actions/checkout@v2 in favour of actions/checkout@v3. It may be worth trying that, but I don't have time for that now.

**Comment by Dopingus** [comment]
I'll check it out.

**Comment by Dopingus** [comment]
index.yaml is updated with 0.2.0 now. Sorry for the inconvenience. I setup branch protection for gh-pages branches and this prevented the Github Action from pushing updates to that branch after the new tag and release were created.
