### ISSUE TITLE
[QUESTION] Installation error ?

### ISSUE THREAD

**Issue by MateusDornelles** [Dopingus/cert-manager-webhook-dynu#13]
Hi, I'm new to Kubernetes, I just installed a new cluster and I'm following the documentation to install the chart :

helm repo add cert-manager-dynu-webhook  https://dopingus.github.io/cert-manager-webhook-dynu
helm repo update
helm install cert-manager-dynu-webhook cert-manager-dynu-webhook/dynu-webhook

   After executing the install command i got the following error : 

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Certificate" in version "cert-manager.io/v1", unable to recognize "": no matches for kind "Issuer" in version "cert-manager.io/v1"]

   Do I missed something  ? 

  Thanks.

**Comment by rbaumgar** [comment]
have you installed cert-manager itself?
Looks like you are missing the cert-manager CRDs
```
$ kubectl get crd -A |grep cert-manager
certificaterequests.cert-manager.io                                    2021-10-29T10:41:25Z
certificates.cert-manager.io                                           2021-10-29T10:41:20Z
challenges.acme.cert-manager.io                                        2021-10-29T10:41:22Z
clusterissuers.cert-manager.io                                         2021-10-29T10:41:18Z
issuers.cert-manager.io                                                2021-10-29T10:41:26Z
orders.acme.cert-manager.io                                            2021-10-29T10:41:29Z
```
